### ISSUE TITLE
[ASK] Update UI data content after some time

### ISSUE THREAD

**Issue by Romaixn** [alienkitty/space.js#1]
Hello! First of all, thank you for this library! I'm using it for a project, and the results are perfect!

Now, I have a need, but I'm not sure if it's possible. I'm using a UI with an info section (just a simple text content), and I’d like to know if it’s possible to update this text after some time? Specifically, to display different information based on user actions.

Thanks 🙏🏻

**Comment by pschroen** [comment]
Good to hear, thanks!

It is possible, I am currently working on some JSDocs for the libraries but it will take some time to document all the possible use cases with examples.

I did recently add an example though that updates the content of the info section, though are you using the library from NPM or GitHub? The reason I ask is I've made a lot of changes since the last release and this example won't work with the current version:

https://space.js.org/examples/graph_markers.html

**Comment by Romaixn** [comment]
@pschroen I'm using NPM version for now :)

**Comment by pschroen** [comment]
Ok, in the meantime you can update the content via the `content` property directly, for example:

```js
ui.info.content.html('Drag away marker to remove');
```

For reference, the next release will include a [`setContent()`](https://github.com/alienkitty/space.js/commit/7b9c025b144c81e121c8688105398fe1e5c7e38a) method.

**Comment by Romaixn** [comment]
Thanks a lot 👑
